<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    protected $fillable = ['home','fh', 'fht', 'h', 'about', 'faq', 'contact', 'signin', 'signup', 'signup_handyman', 'bgs', 'rds','hcs', 'lns', 'lm', 'vd','ston', 's', 'fl','sm', 'fpw', 'cn', 'al','bg', 'dni', 'search', 'ec','sbg','dashboard','edit','reset','logout','cp','np','rnp','chnp','ss','bs','blog','blogs','sie','spe','suf','suph','sue','sup','sucp','fpt','fpe','fpb','con','cop','coe','cor','vdn','vt','gt','dopd','doo','dol','doa','doe','dor','dopr','doc','doci','dosp','don','doem','dom','fname','cup','pp','app','size','md','amf','doct','doad','doph','dofx','dofpl','dotpl','dogpl','dolpl','doeml','doupl','supl','success','dttl','ddesc','ppr','fpr','hml','abouts','faqs','contacts','binfo', 'fn','bn','pc','ad','pn','ct','compname','tn','ba','rg','lang','szc','sc','spzc','spc','spdf','spdt','servP1','servP2','servP3','servP4','servT1','servT2','servT3','servT4','sat','yhtb','acm','ace','st','sr','rtac','nad','ma','chi','chn','chs','chst','chr','csd','cbd','ctot','cac','csf','cpit','cvat','cvatam','cpet','sch','ccs','cc','tyt','cst','tym','htt','cut','ctht','cspo','cfp','cpp','cppt','cpa','hpt','cpt','hmt','cmt','mst','mbt','mbt1','cmpt','eyt','ist','hdt','cdt','pct','rt','sww','pcet','amt','amm','sse','sdt','cpht','cnht','inht','sht','cast','pst','est','ppst','ppest','acst','vbt','past','bst','jcst','rfcst','ayst','uscm','cant','suct','hpbd','hpta','hpa','clit','hit','iat','subtt','apt','art','gtt','it','nit','iservt','istt','isdt','isrt','ibdt','itat','isubtt','isft','ivatt','cypt','cmpn','gtcp','cmpsm','cmpnt','eyn','fet','eyex','eyer','eyp','ish','isam','isn','inct','sct','cpat','clit1','hit1','subtt1','apt1','art1','gtt1','cpvb','past1','ppest1','jcst1','tfst','bst1','rfcst1','ppst1','cpst','cjst','pst1','cast1','est1','rfct','send','ayst1','uscm1','cant1','suct1','it1','nit1','iat1','ert','pgrt','grn','hbsm','cbsm','cbjcm','cnf_btn','ratt','jct','et','acrt','avrt','hpmrt','ft','fct','fit','yt','nt','frt','u1s','u2s','u3s','u4s','u5s','fprt','feyt','fsyt','fbt','avmt','qyt','qnt','rm','pusm','dt','sdesc','pdc','idr','ipcoc','ibd','pwt','pwm','bdp','uit','fte','mie','tpe','hbit','hbipt','hbist','hbidt','hbinit','cbit','cbipt','cbist','cbidt','cbinit','hiwh','rtbh','rft','msst','mssn','ssst','amsst','mssn1','smhn','asst','ssstf','sast','clt','erfct','pumdt','msnt','mput','mrt','yasst','prst','naft','suyp','cpnm','esrt','iagt','tact','pbt','rfevat','hbdih','cbdih','hcp','cmpsm1','yt1','yst','erv','nrv','nmv','niv','fnrv','fnmv','fniv','pcrv','arv','crv','prv','parv','pamv','pacv','grv','cnrv','rnrv','barv','tnrv','euv'];

    public $timestamps = false;
}
