<html>

<body>

@if($type == 'new')

    <p>
        Hi {{$client}},<br><br>Recent activity: A quotation <b>(QUO# {{$quotation_invoice_number}})</b> has been created by Mr./Mrs. <b>{{$username}}</b>. PDF file is attached below. Quotation is waiting for your approval.<br><br>Kind regards,<br><br>Klantenservice Topstoffeerders
    </p>

@elseif($type == 'edit client')

    <p>
        Hi {{$client}},<br><br>Recent activity: A quotation <b>(QUO# {{$quotation_invoice_number}})</b> has been edited by Mr./Mrs. <b>{{$username}}</b> due to your review request. PDF file is attached below.<br><br>Kind regards,<br><br>Klantenservice Topstoffeerders
    </p>

@elseif($type == 'invoice client')

    <p>
        Hi {{$client}},<br><br>Recent activity: An Invoice <b>(INV# {{$quotation_invoice_number}})</b> has been generated by Mr./Mrs. <b>{{$username}}</b>. PDF file is attached below.<br><br>Kind regards,<br><br>Klantenservice Topstoffeerders
    </p>

@endif

</body>

</html>
